### ISSUE TITLE
VSCode Won't Open In WSL When I'm Offline But Does So When I'm Online

### ISSUE THREAD

**Issue by Primepoke** [ubuntu/WSL#353]
### cmd /c ver

Microsoft Windows [Version 10.0.19045.2673]

### wsl --status

Default Distribution: Ubuntu-22.04
Default Version: 1

### Did the problem occur during installation?

- [ ] Yes

### What happened?

When I'm online (connected to the internet) and I turn on vscode in WSL, it opens well. But the minute I'm offline and open vscode in wsl, it does not open the folder/files I'm working on. When I try starting vscode when offline, it displays the following: 

"The editor could not be opened due to an unexpected error: ENOPRO: Np file system provider found for resource 'vscode-remote://wsl%2Bubuntu-22.04/mnt/c/...path/to/file'

When I check the log, it shows many lines of error, notable among them is:

[2023-03-08 13:01:06.864] Error: Unable to retrieve mac address (unexpected format)
[2023-03-08 13:01:06.864] 
[2023-03-08 13:01:06.864] Error: Unable to retrieve mac address (unexpected format)
[2023-03-08 13:01:06.864]     at S (/home/okesiri/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/server/node/server.main.js:63:3251)
[2023-03-08 13:01:06.864]     at v (/home/okesiri/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/server/node/server.main.js:74:8276)
[2023-03-08 13:01:06.864]     at async /home/okesiri/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/server/node/server.main.js:74:8133
[2023-03-08 13:01:06.864]     at Timeout._onTimeout (/home/okesiri/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/server/node/server.main.js:8:12)
[2023-03-08 13:01:06.864]     at listOnTimeout (node:internal/timers:559:17)
[2023-03-08 13:01:06.864]     at processTimers (node:internal/timers:502:7)
[2023-03-08 13:01:06.864] VS Code Server for WSL closed unexpectedly.
[2023-03-08 13:01:07.063] Download in background is enabled
[2023-03-08 13:01:08.945] WSL Daemon exited with code 0

### What was expected?

It is meant to open as it always has. 

### Steps to reproduce

To reproduce error,

1. Turn of internet connection
2. Start VSCode.

### Additional information

[2023-03-08 13:01:06.864] Error: Unable to retrieve mac address (unexpected format)
[2023-03-08 13:01:06.864] 
[2023-03-08 13:01:06.864] Error: Unable to retrieve mac address (unexpected format)
[2023-03-08 13:01:06.864]     at S (/home/okesiri/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/server/node/server.main.js:63:3251)
[2023-03-08 13:01:06.864]     at v (/home/okesiri/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/server/node/server.main.js:74:8276)
[2023-03-08 13:01:06.864]     at async /home/okesiri/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/server/node/server.main.js:74:8133
[2023-03-08 13:01:06.864]     at Timeout._onTimeout (/home/okesiri/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/server/node/server.main.js:8:12)
[2023-03-08 13:01:06.864]     at listOnTimeout (node:internal/timers:559:17)
[2023-03-08 13:01:06.864]     at processTimers (node:internal/timers:502:7)
[2023-03-08 13:01:06.864] VS Code Server for WSL closed unexpectedly.
[2023-03-08 13:01:07.063] Download in background is enabled
[2023-03-08 13:01:08.945] WSL Daemon exited with code 0

**Comment by EduardGomezEscandell** [comment]
Hi, and thanks for your report!

This seems like it may be an issue with WSL itself or maybe VS code. Have you tried eproducing the issue with another distro?

If you haven't, please complete these steps to explore the issue further:

1. Install a non-Ubuntu distro, for example [Debian](https://apps.microsoft.com/store/detail/debian/9MSVKQC78PK6)
2. Run Debian once (either from the store or via powershell `debian.exe`) and complete the setup.
3. Go to VS Code on Windows, click on the green tab at the bottom left (mouse-over text "Open a Remote Window"), click "Connect to WSL using distro"; then select Debian.
4. Do the same experiment as you did for Ubuntu (with/without connection).

Please report the result, as that will determine how to proceed.

**Comment by Primepoke** [comment]
> Hi, and thanks for your report!
> 
> This seems like it may be an issue with WSL itself or maybe VS code. Have you tried eproducing the issue with another distro?
> 
> If you haven't, please complete these steps to explore the issue further:
> 
> 1. Install a non-Ubuntu distro, for example [Debian](https://apps.microsoft.com/store/detail/debian/9MSVKQC78PK6)
> 2. Run Debian once (either from the store or via powershell `debian.exe`) and complete the setup.
> 3. Go to VS Code on Windows, click on the green tab at the bottom left (mouse-over text "Open a Remote Window"), click "Connect to WSL using distro"; then select Debian.
> 4. Do the same experiment as you did for Ubuntu (with/without connection).
> 
> Please report the result, as that will determine how to proceed.

I did as you said. I installed Debian Linux and the result is still the same. I guess the problem must be from WSL or VSCode.

**Comment by EduardGomezEscandell** [comment]
Probably so, feel free to play around updating WSL (maybe reinstalling if data loss is acceptable to you), and if that doesn't fix it, I encourage you to file a bug in one of Microsoft's repos (https://github.com/microsoft/WSL or https://github.com/microsoft/Vscode).

**Comment by Primepoke** [comment]
> Probably so, feel free to play around updating WSL (maybe reinstalling if data loss is acceptable to you), and if that doesn't fix it, I encourage you to file a bug in one of Microsoft's repos (https://github.com/microsoft/WSL or https://github.com/microsoft/Vscode).

Yes, I have updated WSL, uninstalled and reinstalled different distros, disabled and re-enabled WSL. It still presents the same result. I have raised a complaint on https://github.com/microsoft/Vscode and haven't gotten any replies. Maybe I'd have to go raise one on https://github.com/microsoft/WSL.

**Comment by Primepoke** [comment]
There's a temporary fix for this. You can find it here: https://github.com/microsoft/vscode/issues/175878.

The team at Microsoft promise they're coming up with something more permanent.

**Comment by Primepoke** [comment]
The pleasure is mine.
