### ISSUE TITLE
CI failure due failure to launch check-language-support

### ISSUE THREAD

**Issue by CarlosNihelton** [ubuntu/WSL#360]
### cmd /c ver

Microsoft Windows [Version 10.0.25336.1000]

### wsl --status

Distribuição Padrão: Ubuntu-Work
Versão Padrão: 2

Versão do WSL: 1.2.0.0
Versão do kernel: 5.15.90.1
Versão do WSLg: 1.0.51
Versão do MSRDC: 1.2.3770
Versão do Direct3D: 1.608.2-61064218
Versão do DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Versão do Windows: 10.0.25336.1000

### Did the problem occur during installation?

- [ ] Yes

### What happened?

End to end test is failing because subiquity cannot run the `check-language-support` command, causing the test window to hang or quit too early, causing the test to crash. In a real scenario that is not a hard failure, but it's preventing CI to pass.

### What was expected?

End to end test to proceed and quit with success, with locale configured and language packs installed accordingly.

### Steps to reproduce

Follow the e2e.yaml workflow, at the time of this writing it consists of:

1. Checkout the repository
2. Unregister and unninstall Ubuntu Preview, if installed/registered
3. .\e2e\pre-e2e-testing.ps1 -AppID UbuntuPreview -RootfsX64 <a recent lunar image> -CertificateThumbprint <one from your machine>
4. $env:LAUNCHER_REPO_ROOT=<root of the checked out repo>
5. cd e2e/
6. go test .\launchertester\ -timeout 15m -run TestBasicSetup --distro-name Ubuntu-Preview --launcher-name ubuntupreview.exe

### Additional information

The relevant piece of the client log:

```
INFO subiquity_status: WAITING => ApplicationStatus(state: ApplicationState.RUNNING, confirmingTty: , error: null, cloudInitOk: true, interactive: true, echoSyslogId: , logSyslogId: , eventSyslogId: )
INFO subiquity_status: RUNNING => ApplicationStatus(state: ApplicationState.ERROR, confirmingTty: , error: null, cloudInitOk: true, interactive: true, echoSyslogId: , logSyslogId: , eventSyslogId: )
INFO system_shutdown: request reboot (immediate: false)
```

The relevant part of the server log:

```
2023-04-13 13:20:15,895 ERROR system_setup.server.controllers.configure:160 Language selector data dir /snap/subiquity/current/usr/share/language-selector seems not to be part of the snap.
2023-04-13 13:20:15,895 DEBUG subiquitycore.utils:96 arun_command called: ['check-language-support', '-d', '/usr/share/language-selector', '-l', 'en_US']
2023-04-13 13:20:15,898 ERROR root:37 finish: subiquity/Configure/configure: FAIL: [Errno 2] No such file or directory: 'check-language-support'
2023-04-13 13:20:15,898 ERROR subiquity.server.server:422 top level error
Traceback (most recent call last):
  File "/snap/subiquity/current/lib/python3.10/site-packages/system_setup/server/controllers/shutdown.py", line 47, in _wait_install
    await self.app.controllers.Install.install_task
FileNotFoundError: [Errno 2] No such file or directory: 'check-language-support'
2023-04-13 13:20:15,900 ERROR subiquity.server.server:422 top level error
Traceback (most recent call last):
  File "/snap/subiquity/current/lib/python3.10/site-packages/system_setup/server/controllers/shutdown.py", line 47, in _wait_install
    await self.app.controllers.Install.install_task
FileNotFoundError: [Errno 2] No such file or directory: 'check-language-support'
2023-04-13 13:20:15,900 INFO root:37 finish: subiquity/Meta/status_GET: SUCCESS: 200 {"state": "ERROR", "confirming_tty": "", "error": null, "cloud_init_ok": true...
2023-04-13 13:20:15,901 INFO aiohttp.access:206 127.0.0.1 [13/Apr/2023:13:20:15 +0000] "GET /meta/status?cur=%22RUNNING%22 HTTP/1.1" 200 353 "-" "Dart/2.19 (dart:io)"
2023-04-13 13:20:15,901 ERROR subiquity.server.server:422 top level error
Traceback (most recent call last):
  File "/snap/subiquity/current/lib/python3.10/site-packages/subiquity/server/server.py", line 406, in _run_error_cmds
    await report._info_task
AttributeError: 'NoneType' object has no attribute '_info_task'
```

The cause is related to the fact that, since the language-selector-common package is not part of the snap, but seeded. The data directory has been addressed, but the command is not in PATH.

**Comment by CarlosNihelton** [comment]
Fixed by https://github.com/canonical/subiquity/pull/1657
