### ISSUE TITLE
Ubuntu 24.04's `do-release-upgrade` requires a working `snap list` which is not there for WSLv1 - instead should just skip not working `snap` / `snap list` / `snapd`

### ISSUE THREAD

**Issue by vadimkantorov** [ubuntu/WSL#493]
### cmd /c ver

Microsoft Windows [Version 10.0.22631.4037]

### wsl --status

C:\Users\vadim>wsl --status
Default Distribution: Ubuntu
Default Version: 2

C:\Users\vadim>wsl -l -v
  NAME            STATE           VERSION
* Ubuntu          Stopped         2
  UbuntuWSL1      Stopped         1
  Ubuntu-24.04    Running         1

### Did the problem occur during installation?

- [ ] Yes

### What happened?

- I have a Ubuntu-22.04/WSLv1 distro `UbtuntuWSL1`
- `sudo do-release-upgrade` fails with stack trace somewhere after `noble.tar.gz` is extracted:
```
Traceback (most recent call last):
  File "/tmp/ubuntu-release-upgrader-uqmd8iby/noble", line 8, in <module>
    sys.exit(main())
  File "/tmp/ubuntu-release-upgrader-uqmd8iby/DistUpgrade/DistUpgradeMain.py", line 241, in main
    if app.run():
  File "/tmp/ubuntu-release-upgrader-uqmd8iby/DistUpgrade/DistUpgradeController.py", line 2642, in run
    return self.fullUpgrade()
  File "/tmp/ubuntu-release-upgrader-uqmd8iby/DistUpgrade/DistUpgradeController.py", line 2447, in fullUpgrade
    if not self.doPostInitialUpdate():
  File "/tmp/ubuntu-release-upgrader-uqmd8iby/DistUpgrade/DistUpgradeController.py", line 1438, in doPostInitialUpdate
    self.quirks.run("PostInitialUpdate")
  File "/tmp/ubuntu-release-upgrader-uqmd8iby/DistUpgrade/DistUpgradeQuirks.py", line 102, in run
    func()
  File "/tmp/ubuntu-release-upgrader-uqmd8iby/DistUpgrade/DistUpgradeQuirks.py", line 127, in noblePostInitialUpdate
    self._test_and_fail_on_tpm_fde()
  File "/tmp/ubuntu-release-upgrader-uqmd8iby/DistUpgrade/DistUpgradeQuirks.py", line 1898, in _test_and_fail_on_tpm_fde
    snap_list = subprocess.check_output(['snap', 'list'])
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['snap', 'list']' returned non-zero exit status 1.
```
- This happens because `snap list` errors out with exit code 1 and prints: `Interacting with snapd is not yet supported on Windows Subsystem for Linux 1. This command has been left available for documentation purposes only.`
- I worked around and managed to get Ubuntu-24.04/WSLv1 by installing it fresh from MS Store and then forcing WSLv1, but this is not ideal as we have to set up the distro from scratch

Related issue I created in MS's repo:
- https://github.com/microsoft/WSL/issues/11982

### What was expected?

On Ubuntu-22.04/WSLv1 `sudo do-release-upgrade` should succeed and bypass not working `snap list`, maybe `snap list` could be stubbed out, or better - the upgrader script should handle this error. On WSLv1 `snap`/`snapd` and snap apps are not supported, so they need not any upgrades, and this should be simply skipped in the upgrade process

### Steps to reproduce

N/A - explained above (have Ubuntu-22.04 + WSLv1 and launch `sudo do-release-upgrade`)

**Comment by vadimkantorov** [comment]
In /tmp/ubuntu-release-upgrader-t8sg0mg9/DistUpgrade/DistUpgradeQuirks.py:
```python
     def _test_and_fail_on_tpm_fde(self):
        """
        LP: #2065229
        """
        try:
            snap_list = subprocess.check_output(['snap', 'list'])
            snaps = [s.decode().split()[0] for s in snap_list.splitlines()]
        except FileNotFoundError:
            # snapd not installed?
            return

```

I think `except FileNotFoundError:` should be extended to `except:`

**Comment by ZupoLlask** [comment]
I guess I'm finding another fellow that appreciates WSL1 approach... ;-)

**Comment by sephiroth-j** [comment]
I use wsl2 but I am getting the same error. 😕

**Comment by jibel** [comment]
Thanks for your report. I filed https://bugs.launchpad.net/ubuntu/+source/ubuntu-release-upgrader/+bug/2080233 upstream to address this issue in Ubuntu release upgrader.

**Comment by vadimkantorov** [comment]
Another suggestion:
- allow to specify the non-random temp path for `DistUpgrade/DistUpgradeQuirks.py`
- fix the problem in `_test_and_fail_on_tpm_fde` in `DistUpgrade/DistUpgradeQuirks.py` and in general make all these hacks for defensive to eat up unexpected exceptions or allow to continue on errors, it seems that many people have stumbled on various problems in `DistUpgrade/DistUpgradeQuirks.py`. So maybe putting this script / upgrade tools on a GitHub repo would allow regular users to report problems faster...

@jibel In the bug filed above two problems appear mixed:
1. bug in `_test_and_fail_on_tpm_fde` which crashes on unexpected return code by `snap list`
2. bug in `apt` which tries to run systemd-postinstall scripts whereas `systemd` is disabled

Btw my distro became broken after this upgrade attempt, and `--fix-broken-install` did not help as it also tries to run systemd-postinstall scripts and cannot. Luckily, I installed a fresh Ubuntu24.04 distro from Microsoft Store and switched it to WSLv1 successfully. But of course, this upgrade experience is not very nice :(

**Comment by vadimkantorov** [comment]
> I filed https://bugs.launchpad.net/ubuntu/+source/ubuntu-release-upgrader/+bug/2080233 upstream to address this issue in Ubuntu release upgrader.

Could you please add in there investigated details about the `DistUpgrade/DistUpgradeQuirks.py` being problematic and its function `_test_and_fail_on_tpm_fde` being too conservative? That method is designed to work if `snap` is not present, but unfortunately fails to continue if `snap` exists, but `snap list` returns a stubbed message / non-zero exit code

**Comment by SharakPL** [comment]
I've just tried to `do-release-upgrade` on WSL 2 and got similar result:
```
Checking for a new Ubuntu release

= Welcome to Ubuntu 24.04 LTS 'Noble Numbat' =

The Ubuntu team is proud to announce Ubuntu 24.04 LTS 'Noble Numbat'.

To see what's new in this release, visit:
  https://wiki.ubuntu.com/NobleNumbat/ReleaseNotes

Ubuntu is a Linux distribution for your desktop or server, with a fast
and easy install, regular releases, a tight selection of excellent
applications installed by default, and almost any other software you
can imagine available through the network.

We hope you enjoy Ubuntu.

== Feedback and Helping ==

If you would like to help shape Ubuntu, take a look at the list of
ways you can participate at

  http://www.ubuntu.com/community/participate/

Your comments, bug reports, patches and suggestions will help ensure
that our next release is the best release of Ubuntu ever.  If you feel
that you have found a bug please read:

  http://help.ubuntu.com/community/ReportingBugs

Then report bugs using apport in Ubuntu.  For example:

  ubuntu-bug linux

will open a bug report in Launchpad regarding the linux package.

If you have a question, or if you think you may have found a bug but
aren't sure, first try asking on the #ubuntu or #ubuntu-bugs IRC
channels on Libera.Chat, on the Ubuntu Users mailing list, or on the
Ubuntu forums:

  http://help.ubuntu.com/community/InternetRelayChat
  http://lists.ubuntu.com/mailman/listinfo/ubuntu-users
  http://www.ubuntuforums.org/


== More Information ==

You can find out more about Ubuntu on our website, IRC channel and wiki.
If you're new to Ubuntu, please visit:

  http://www.ubuntu.com/


To sign up for future Ubuntu announcements, please subscribe to Ubuntu's
very low volume announcement list at:

  http://lists.ubuntu.com/mailman/listinfo/ubuntu-announce


Continue [yN] y
```
```
Reading cache

Checking package manager
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Hit http://archive.ubuntu.com/ubuntu jammy InRelease
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:2 https://cli.github.com/packages stable InRelease [3917 B]
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [2313 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1185 kB]
Get:7 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [2077 kB]
Hit https://ppa.launchpadcontent.net/git-core/ppa/ubuntu jammy InRelease
Hit https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy InRelease
Get:8 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [961 kB]
Fetched 6924 kB in 0s (0 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
error: cannot list snaps: cannot communicate with server: Get "http://localhost/v2/snaps": dial unix /run/snapd.socket: connect: no such file or directory

Traceback (most recent call last):
  File "/tmp/ubuntu-release-upgrader-etf22dfk/noble", line 8, in <module>
    sys.exit(main())
  File "/tmp/ubuntu-release-upgrader-etf22dfk/DistUpgrade/DistUpgradeMain.py", line 241, in main
    if app.run():
  File "/tmp/ubuntu-release-upgrader-etf22dfk/DistUpgrade/DistUpgradeController.py", line 2662, in run
    return self.fullUpgrade()
  File "/tmp/ubuntu-release-upgrader-etf22dfk/DistUpgrade/DistUpgradeController.py", line 2467, in fullUpgrade
    if not self.doPostInitialUpdate():
  File "/tmp/ubuntu-release-upgrader-etf22dfk/DistUpgrade/DistUpgradeController.py", line 1438, in doPostInitialUpdate
    self.quirks.run("PostInitialUpdate")
  File "/tmp/ubuntu-release-upgrader-etf22dfk/DistUpgrade/DistUpgradeQuirks.py", line 102, in run
    func()
  File "/tmp/ubuntu-release-upgrader-etf22dfk/DistUpgrade/DistUpgradeQuirks.py", line 127, in noblePostInitialUpdate
    self._test_and_fail_on_tpm_fde()
  File "/tmp/ubuntu-release-upgrader-etf22dfk/DistUpgrade/DistUpgradeQuirks.py", line 1906, in _test_and_fail_on_tpm_fde
    snap_list = subprocess.check_output(['snap', 'list'])
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['snap', 'list']' returned non-zero exit status 1.
=== Command terminated with exit status 1 (Fri Feb  7 18:33:12 2025) ===
```
I've used this command several times before without problems.
Updated WSL from Microsoft Store and tried again, but the result was the same.

![Image](https://github.com/user-attachments/assets/c7a4edea-2d31-471d-957e-2fefdb653666)

**$ ubuntu-bug linux**

> *** Collecting problem information
> 
> The collected information can be sent to the developers to improve the
> application. This might take a few minutes.
> ...........dpkg-query: no packages found matching linux-image-5.15.167.4-microsoft-standard-WSL2
> .cloud-init run data not found on system. Unable to add cloud-specific data.
> 
> 
> *** Problem in linux-image-5.15.167.4-microsoft-standard-WSL2
> 
> The problem cannot be reported:
> 
> This report is about a package that is not installed.
